### ISSUE TITLE
Cannot read property 'checked' of undefined

### ISSUE THREAD

**Issue by cjroebuck** [ziad-saab/react-checkbox-group#11]
Works fine when clicking the first Checkbox in a list. 

But I'm getting this error when clicking a Checkbox which is > 0 index in a list. 

Change line 173 of the test to:

`var box = wrapper.querySelector('input[value="pineapple"]');`
(i.e. imitating selecting the 2nd checkbox in the list)

to see for yourself:

    ReactCheckboxGroup Calls `onChange` with the correct new value:
     TypeError: Cannot read property 'checked' of undefined
      at [object Object].onCheckboxChange (react-checkbox-group.jsx:37:9)
      at Object.LinkedValueUtils.executeOnChange (node_modules/react/lib/LinkedValueUtils.js:129:34)
      at ReactDOMComponent._handleChange (node_modules/react/lib/ReactDOMInput.js:106:38)
      at Object.invokeGuardedCallback [as invokeGuardedCallbackWithCatch] (node_modules/react/lib/ReactErrorUtils.js:27:12)
      at executeDispatch (node_modules/react/lib/EventPluginUtils.js:77:21)
      at Object.executeDispatchesInOrder (node_modules/react/lib/EventPluginUtils.js:102:5)
      at executeDispatchesAndRelease (node_modules/react/lib/EventPluginHub.js:43:22)
      at executeDispatchesAndReleaseSimulated (node_modules/react/lib/EventPluginHub.js:51:10)
      at forEachAccumulated (node_modules/react/lib/forEachAccumulated.js:25:8)
      at Object.EventPluginHub.processEventQueue (node_modules/react/lib/EventPluginHub.js:257:7)
      at node_modules/react/lib/ReactTestUtils.js:406:22
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
      at Object.change (node_modules/react/lib/ReactTestUtils.js:404:18)
      at Context.<anonymous> (react-checkbox-group_spec.js:174:14)

**Comment by ziad-saab** [comment]
@cjroebuck thanks for the bug report. I'm going to add this failing test and fix it.

**Comment by ziad-saab** [comment]
@cjroebuck this is fixed in 1.0.2. Please update your package and thanks again for the bug report :)

**Comment by cjroebuck** [comment]
Thanks, I spent a bit of time trying to fix it myself but didn't get what was causing the issue. That was quite a subtle bug and I'm surprised anyone was able to use the component with this bug!

**Comment by ziad-saab** [comment]
@cjroebuck thanks again for catching it!
